sudo: false
language: go
matrix:
  allow_failures:
  - go: tip
  include:
  - go: 1.5.4
    env: GO15VENDOREXPERIMENT=1
  - go: 1.6.3
  - go: 1.7.1
    env: SEND_COVERAGE=1
  - go: tip
before_install:
- go get github.com/mattn/goveralls
- go get github.com/modocache/gover
- go get github.com/laher/goxc
install:
- make prepare
script:
- if ([ "$SEND_COVERAGE" == "1" ]); then make test-cover; else make test; fi
- make fmt-check
- if ([ "$TRAVIS_GO_VERSION" != "1.5.4" ]); then make lint; fi
- make vet
before_deploy:
- goxc
deploy:
  provider: releases
  api_key:
    secure: 0Vi3Qp+7qaTYCOgDMKgByCdDeu6sy5hPGKguGAqUwjfo2y0/doTThN42dO1PF65H/VIJKWVX5LV8l1ArQCYTOvSWSVXERtOxFLhaSkb3l547lDMDDRZcyayqreKpm9gxbgdnBTHonyhYtMpvhfgmtJjB/G1LN2qu7oaafShFfjmT4yLm1p6Jpp4et3Rl0mw2gFnDBEn3xDRfU4dmUxywSKIYL6wKeC2h7lvPWz38iuf6OtS5jVLPSknPQo50veOM6kx7gCvYFE0StQcqy36ob1tzlCyPp45PSE+RPItPMaCQmKTimdIdtv34gxqFXr8Xi236kk2llcJ1XV7aI+NjVUrZtL9tX32cuaw6LxHGLRD48ajQi70IqDuyI5NieCwPexdgxh3BldLEp2tYOHnXzXtjpw6taZTCoZIQkoEBKLmvL6mBWZfjWnb/WV3naN5UhldTyMrYxD1BQpLm10VV+CFiwO2/sqd3le7BeLG4ns2L9MkV5YndH+We/gUhbR5lCTcWyZDeOa33hq3N/+mvGp3VXseSaD87svPMF5pvsxxdwfnSWZmdTftlrUKT2gNUQmUsdGrfj6vU4u+N69IVsLpQ8YhGOjVFQXWTMtVN71ZTjL2zg5MIcmMe+aAAZAKKA7b8NnZEoN1UcXZfwthrf7LDyeu0Slsj+HQq8jRFHd4=
  file_glob: true
  file:
  - $HOME/gopath/bin/metrics-fetcher-xc/*/metrics-fetcher_*.tar.gz
  - $HOME/gopath/bin/metrics-fetcher-xc/*/metrics-fetcher_*.deb
  skip_cleanup: true
  on:
    tags: true
    go: 1.7.1
after_success:
- if ([ "$SEND_COVERAGE" == "1" ]); then gover && $HOME/gopath/bin/goveralls -service=travis-ci
  -coverprofile=gover.coverprofile; fi
os:
- linux
notifications:
  email: false