sudo: false
language: go
matrix:
  allow_failures:
  - go: tip
  include:
    - go: 1.5.4
      env: GO15VENDOREXPERIMENT=1
    - go: 1.6.3
    - go: 1.7.1
      env: SEND_COVERAGE=1
    - go: tip
env:
  global:
    secure: jyEoRXyOOxEoYvGO07yAfjAysNnzChAWbvMjbx3MXnMLIB3dyYz8+adZwFXqLBdxoLZyOZVwhol8X9i9Ql0zNaSLg41Oi4z+aSFFUp1rP0mt9vNqY5F5L04vGdXUTX/aUFxVlXfwDlc6BeP0qfDoFyEKBARimd94O7pw97zN/AxwsbW8Npp8tGJRUxgV5Mb//3+pPPvUP0hpt8h7WpOz38ALFOVU/K3SBkb1usBepHGmmnhXrP5TrwDtGUnDGhR/MVAgoW8DriQeOiEYfYROG98IZ8909sWkVUdgOMq/CfqHykZpoljvKYscrMMLfYLYKYTW87Cvq7kjfj1FYRHNr5fhDKqB3tyX12BaqyAsDL4NoH1nBDW5p+Oviq7g0I5V1ZomVpKp++KmPVGuhV7ecNYTQ93SKtpOdlkkSMh8T3F5ZB1BZz7vkbVHspn+iXl+KCPb2y4ySk+xBGrVcY7/Z21vA2/IzOkC+120rMwUB4rpujvR1nlVS824r1qTH4rxkreWpafYyreM3eUz6dCz9hcKlAwbdtSmOpyyH2E6EBHRrLwGygaLqd651ccZnlX/Cf9NzGrwghHqwoIewk0qBstiVadVsopgmL+wWP6xYjEtQ+ZSyz5xsJGDDZcnkJM0Ut6tYODuGe+JpqFzVpJGAHo1siZfaxA0fjy64E/cyL0=
before_install:
- go get github.com/mattn/goveralls
- go get github.com/modocache/gover
install:
- make prepare
script:
- if ([ "$SEND_COVERAGE" == "1" ]); then make test-cover; else make test; fi
- make fmt-check
- make lint
- make vet
after_success:
- if ([ "$SEND_COVERAGE" == "1" ]); then gover && $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile; fi
os:
- linux
notifications:
  email: false
