sudo: false
language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO15VENDOREXPERIMENT=1
install:
  - make prepare

script:
  - make test

after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - make lint
  - make vet

os:
  - linux

notifications:
  email: false
