resources:
  - name: metrics-fetcher-github
    type: git
    source:
      uri: https://github.com/Wikia/metrics-fetcher.git
      branch: master

jobs:
  - name: test
    plan:
      - get: metrics-fetcher-github
        trigger: true
      - task: test
        file: metrics-fetcher-github/ci/test.yml
  - name: lint
    plan:
      - get: metrics-fetcher-github
        trigger: true
      - task: lint
        file: metrics-fetcher-github/ci/lint.yml
  - name: build
    plan:
      - aggregate:
        - get: metrics-fetcher-github
          trigger: true
          passed: [test, lint]
      - task: build
        file: metrics-fetcher-github/ci/build.yml
